import Navbar from "@/components/Navbar";
import "./globals.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <div className="flex min-h-screen">
        <Navbar />
        <body>{children}</body>
      </div>
    </html>
  );
}
